#! /bin/sh

PACKAGE=mate-user-guide;

# normal translations for the package
make -C po $PACKAGE.pot && mv po/$PACKAGE.pot .
sed -i "/#, fuzzy/d" $PACKAGE.pot
sed -i 's/charset=CHARSET/charset=UTF-8/g' $PACKAGE.pot

# translations for the quide itself
rm -f $PACKAGE/$PACKAGE.pot &&
make -C $PACKAGE $PACKAGE.pot
